### PR TITLE
Add vcgGeodesicPath function

### PR DESCRIPTION
**Pull request by dfsp-spirit**
This PR adds a new function, `vcgGeodesicPath`. The function uses the distance vector and pointers provided by `vcglib` during geodesic distance computations to obtain the path and its length: `vcgGeodesicPath(x, source, targets, maxdist = 1e+06)`. Usage example to compute 2 paths and their length to vertex 50 on humface:

    data(humface)
    p = vcgGeodesicPath(humface,50,c(500,5000))
    p$paths[[1]];   # The path 50..500
    p$geodist[500]; # Its path length.

Note: I added that example to the `@examples` section in the function documentation, but it is hard to tell from that whether reasonable paths are computed. One can visualize the path in fsbrain like this:

    devtools::install_github('dfsp-spirit/fsbrain', ref='geodesic')

Then:

    library("fsbrain"); library("Rvcg");
    data(humface); p = vcgGeodesicPath(humface,50,as.integer(seq(1, ncol(humface$vb), length.out=10)));
    vis.fs.surface(humface); fsbrain::vis.paths.along.verts(humface, p$paths);

This should give the following image:

Rvcg_geodesic_path

If you want any changes please let me know. I was unsure about 2 things:
* Whether the R function should really be called `vcgGeodesicPath` (as opposed to something like `geodesicPath`), because there is no VCGLIB C++ function with that or a similar name. 
* Whether I should provide unit tests, as this would have required suggesting a new package (`testthat`) in the `DESCRIPTION`. I will gladly add them if you prefer that.

Tim

### CODE REVIEW

**Comment by zarquon42b** [comment]
Hi Tim,
this looks great. Good work! Thanks a lot for your efforts. I'll test it and merge it asap.
>Whether the R function should really be called vcgGeodesicPath (as opposed to something like geodesicPath), because there is no VCGLIB C++ function with that or a similar name.
I am using the prefix for functions that call C++ code from vcglib directly as all of them are wrappers and not direct calls of vcglib classes. So this is fine.
>Whether I should provide unit tests, as this would have required suggesting a new package (testthat) in the DESCRIPTION. I will gladly add them if you prefer that.
I am hesitant to include those to Rvcg because submitting Rvcg to CRAN is always a nightmare (as it is already) and I try to run as little code as possible to avoid CRAN finding some nitpicky issue about some minor memleaks or so. ;)

Please also add yourself to the Authors section in DESCRIPTION. Like 
`person("Schaefer", "Tim",,, c("ctb"))` - I'd try to avoid Umlauts.

**Comment by dfsp-spirit** [comment]
Great to hear that you like the new function.

* I feel your pain regarding CRAN submission, it has become worse and worse over time. For my packages, I have lots of tests but I do not run them on CRAN anymore (via `testthat::skip_on_cran()`). The CRAN team even requested that I turn them off on CRAN because they feel they take too long. Whatever, I won't add unit tests then.
* Okay, I've added myself to the DESCRIPTION file

**Comment by zarquon42b** [comment]
Hi Tim, the example of this function is creating a segfault in some clang installs. Do you have an idea, what might provoke this?
https://cran.r-project.org/web/checks/check_results_Rvcg.html

**Comment by dfsp-spirit** [comment]
I am using GCC, but I will install clang and have a look.

**Comment by zarquon42b** [comment]
I just got an email from Ripley stating:
> Dear maintainer,
>
> Please see the problems shown on
> <https://cran.r-project.org/web/checks/check_results_Rvcg.html>.
>
> Please correct before 2021-09-17 to safely retain your package on CRAN.
>
> The CRAN Team
>
> The segfaults are new in 0.20 and also seen on Intel macOS.

The dirty fix would be to simply remove the example but this will lead to segfaults for mac users when they try to apply it.

**Comment by zarquon42b** [comment]
I created a dedicated issue https://github.com/zarquon42b/Rvcg/issues/26

**Pull request merged**
